### PR TITLE
Add Modal for Sub Confirm Page

### LINKED ISSUE #2: [Enhancement] Modal For SubScribe Page
Would be great to have a modal instead of going to a next page for subscribing the plan choosed. More user friendly I would say. Just an idea ;)

### PR DESCRIPTION
**Pull request by Dark1z**
Fix #2 

Add Modal for Group Subscription Confirm Page

I have tested this on Group Subscription v`1.2.0-beta`,
I have done the required changes for Group Subscription v`1.3.0-beta4`,
hence kindly do a through check/test for Group Subscription v`1.3.0-beta4`.

You can do further changes as-per your wish,
like JavaScript changes for `stevotvr_groupsub_set_term_id(...)` function, ...etc...

Best regards 👍

### CODE REVIEW

**Comment by stevotvr** [comment]
What does this do? Can you post some screenshots?

**Comment by dark-1** [comment]
> What does this do? Can you post some screenshots?

@stevotvr ,
Here for Group Subscription v`1.2.0-beta` : 

which fix #2 

Best regards 👍

**Comment by stevotvr** [comment]
Thanks for the screenshot. Can you update it so that it doesn't use inline JavaScript?

**Comment by dark-1** [comment]
@stevotvr ,

I tried with Group Subscription v`1.3.0-beta4` ,
it's impossible to create Modal with above version.

It works with Group Subscription v`1.2.0-beta`,
since it does not need PayPal SDK js.

Close this PR & #2 , after reading.

Best regards 👍

**Comment by Dark1z** [comment]
@FlashTVR || @StrontiumDogeh ,

Anybody active here ???
Also, Who is going to manage this project henceforth ???

Best regards 👍

**Comment by FlashTVR** [comment]
@Dark1z Thanks for the ping, I didn't notice there were open PRs.

We're still settling into our "new normal" without Stevo. None of us are very familiar with this code yet, I'll try to review your commits soon.

**Comment by Dark1z** [comment]
> @Dark1z Thanks for the ping, I didn't notice there were open PRs.
> 
> We're still settling into our "new normal" without Stevo. None of us are very familiar with this code yet, I'll try to review your commits soon.

Kindly check this comment : https://github.com/TheVilleOrg/phpbb-groupsub/pull/37#issuecomment-775784383

then close this PR along with this Issue : https://github.com/TheVilleOrg/phpbb-groupsub/issues/2

Best regards 👍

**Pull request closed without merging**
